//* 채팅 페이크 데이터
export const fakeData = [
  {
    user: '관리자',
    message: '관리자입니다.',
  },
  {
    user: '관리자',
    message: '안녕하세요.',
  },
];

//* 메인 화면의 자유게시판 박스 페이크 데이터
export const free_fake_data = {
  id: 'xcqWMXlUUx1',
  content: '자유게시판 글을 보여줍니다.',
  category: 'free',
};

//* 메인 화면의 갤러리 박스 페이크 데이터
export const gallery_fake_data = {
  id: 'tD7EyBmZcLH',
  src: '/images/1672023331502-3o43kwpfrii.jpg',
  content: '재택근무 데스크 ...',
  category: 'gallery',
};

//* 메인 화면의 유튜브 박스 페이크 데이터
export const youtube_fake_data = {
  id: '2RxtV2TkPZo',
  src: '/images/hqdefault.jpg',
  content: `TAEYEON 태연 '...`,
  category: 'youtube',
};

//* 메인 화면의 공지사항 박스 페이크 데이터
export const notice_fake_data = {
  id: 'pqIN9QnFjcA',
  content: '공지사항 글을 보여줍니다.',
  category: 'notice',
};

//* 최근게시글 페이크 테이터
export const new_board_fake_data = [
  {
    id: 'xcqWMXlUUx1',
    title: '고윤혁 테스트 게시글 입니다.',
    user_name: '고윤혁',
    permission_name: '관리자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '테스트 제니 게시글 입니다.',
    user_name: '제니',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '지수 테스트 게시글 입니다.',
    user_name: '지수',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '테스트 우정잉 게시글 입니다.',
    user_name: '우정잉',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'youtube',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '곽튜브 테스트 게시글 입니다.',
    user_name: '곽튜브',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '테스트 강지영 게시글 입니다.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'gallery',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '강지영 테스트 게시글 입니다.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '태연 테스트 게시글 입니다.',
    user_name: '태연',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '유재석 테스트 게시글 입니다.',
    user_name: '유재석',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '유재석 테스트 게시글 입니다.',
    user_name: '유재석',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '유재석 테스트 게시글 입니다.',
    user_name: '유재석',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
];

//* 자유게시판 페이크 테이터
export const free_board_fake_data = [
  {
    id: 'xcqWMXlUUx1',
    title: '고윤혁 테스트 게시글 입니다.',
    user_name: '고윤혁',
    permission_name: '관리자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '테스트 제니 게시글 입니다.',
    user_name: '제니',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '지수 테스트 게시글 입니다.',
    user_name: '지수',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '테스트 우정잉 게시글 입니다.',
    user_name: '우정잉',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '곽튜브 테스트 게시글 입니다.',
    user_name: '곽튜브',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '테스트 강지영 게시글 입니다.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '강지영 테스트 게시글 입니다.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '태연 테스트 게시글 입니다.',
    user_name: '태연',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
  {
    id: 'xcqWMXlUUx1',
    title: '유재석 테스트 게시글 입니다.',
    user_name: '유재석',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'free',
  },
];

//* 유머 페이크 테이터
export const humor_board_fake_data = [
  {
    id: 'pqIN9QnFjcA',
    title: '고윤혁 유머 게시글 입니다.',
    user_name: '고윤혁',
    permission_name: '관리자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '유머 제니 게시글 입니다.',
    user_name: '제니',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '지수 유머 게시글 입니다.',
    user_name: '지수',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '유머 우정잉 게시글 입니다.',
    user_name: '우정잉',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '곽튜브 유머 게시글 입니다.',
    user_name: '곽튜브',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '유머 강지영 게시글 입니다.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '강지영 유머 게시글 입니다.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '태연 유머 게시글 입니다.',
    user_name: '태연',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '유재석 유머 게시글 입니다.',
    user_name: '유재석',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'humor',
  },
];

//* 공지사항 페이크 테이터
export const notice_board_fake_data = [
  {
    id: 'pqIN9QnFjcA',
    title: '고윤혁 테스트 게시글 입니다.',
    user_name: '고윤혁',
    permission_name: '관리자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '테스트 제니 게시글 입니다.',
    user_name: '제니',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '지수 테스트 게시글 입니다.',
    user_name: '지수',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '테스트 우정잉 게시글 입니다.',
    user_name: '우정잉',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '곽튜브 테스트 게시글 입니다.',
    user_name: '곽튜브',
    permission_name: '사용자',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '테스트 강지영 게시글 입니다.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '강지영 테스트 게시글 입니다.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '태연 테스트 게시글 입니다.',
    user_name: '태연',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
  {
    id: 'pqIN9QnFjcA',
    title: '유재석 테스트 게시글 입니다.',
    user_name: '유재석',
    permission_name: '회원',
    datetime: '02-28',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    category: 'notice',
  },
];

//* 갤러리 카드 페이크 데이터
export const gallery_card_fake_data = [
  {
    id: 'tD7EyBmZcLH',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    title: '강지영 아나운서 보고가세요.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    category: 'gallery',
  },
  {
    id: 'tD7EyBmZcLH',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    title: '강지영 아나운서 보고가세요.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    category: 'gallery',
  },
  {
    id: 'tD7EyBmZcLH',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    title: '강지영 아나운서 보고가세요.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    category: 'gallery',
  },
  {
    id: 'tD7EyBmZcLH',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    title: '강지영 아나운서 보고가세요.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    category: 'gallery',
  },
  {
    id: 'tD7EyBmZcLH',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    title: '강지영 아나운서 보고가세요.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    category: 'gallery',
  },
  {
    id: 'tD7EyBmZcLH',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    title: '강지영 아나운서 보고가세요.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    category: 'gallery',
  },
  {
    id: 'tD7EyBmZcLH',
    src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
    title: '강지영 아나운서 보고가세요.',
    user_name: '강지영',
    permission_name: '아나운서',
    datetime: '02-28',
    category: 'gallery',
  },
];

//* 유튜브 카드 페이크 데이터
export const youtube_card_fake_data = [
  {
    id: '2RxtV2TkPZo',
    src: '/images/hqdefault.jpg',
    title: 'INVU 뮤직비디오',
    user_name: '태연',
    permission_name: '가수',
    datetime: '02-28',
    category: 'youtube',
  },
  {
    id: '2RxtV2TkPZo',
    src: '/images/hqdefault.jpg',
    title: 'INVU 뮤직비디오',
    user_name: '태연',
    permission_name: '가수',
    datetime: '02-28',
    category: 'youtube',
  },
  {
    id: '2RxtV2TkPZo',
    src: '/images/hqdefault.jpg',
    title: 'INVU 뮤직비디오',
    user_name: '태연',
    permission_name: '가수',
    datetime: '02-28',
    category: 'youtube',
  },
  {
    id: '2RxtV2TkPZo',
    src: '/images/hqdefault.jpg',
    title: 'INVU 뮤직비디오',
    user_name: '태연',
    permission_name: '가수',
    datetime: '02-28',
    category: 'youtube',
  },
  {
    id: '2RxtV2TkPZo',
    src: '/images/hqdefault.jpg',
    title: 'INVU 뮤직비디오',
    user_name: '태연',
    permission_name: '가수',
    datetime: '02-28',
    category: 'youtube',
  },
  {
    id: '2RxtV2TkPZo',
    src: '/images/hqdefault.jpg',
    title: 'INVU 뮤직비디오',
    user_name: '태연',
    permission_name: '가수',
    datetime: '02-28',
    category: 'youtube',
  },
  {
    id: '2RxtV2TkPZo',
    src: '/images/hqdefault.jpg',
    title: 'INVU 뮤직비디오',
    user_name: '태연',
    permission_name: '가수',
    datetime: '02-28',
    category: 'youtube',
  },
  {
    id: '2RxtV2TkPZo',
    src: '/images/hqdefault.jpg',
    title: 'INVU 뮤직비디오',
    user_name: '태연',
    permission_name: '가수',
    datetime: '02-28',
    category: 'youtube',
  },
];

//* 상세 게시글 페이크 데이터
export const post_data = {
  src: 'https://pbs.twimg.com/media/C_j5ZDYUIAAf4Ov.jpg:large',
  content: '강지영 아나운서가 이상형\n진짜 청순 섹시 지적이미지 반전 보이스 다 있음\n영어도 잘함\n완벽 그 잡채',
};

//* 상세 유튜브 페이크 데이터
export const youtube_data = {
  src: 'https://i.ytimg.com/vi_webp/AbZH7XWDW_k/maxresdefault.webp',
};
